# Generated by Django 2.1.13 on 2019-11-04 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Значение по показателю',
                'verbose_name_plural': 'Значения по показателям',
            },
        ),
        migrations.CreateModel(
            name='Indicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_indicator', models.CharField(max_length=50)),
                ('indicator', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Показатель',
                'verbose_name_plural': 'Показатели',
            },
        ),
        migrations.CreateModel(
            name='TechDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_department', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('office', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Офис',
                'verbose_name_plural': 'Офисы',
            },
        ),
        migrations.AddField(
            model_name='departmentoffice',
            name='id_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Indicate'),
        ),
        migrations.AddField(
            model_name='departmentoffice',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.TechDepartment'),
        ),
    ]
